### ISSUE TITLE
请教WPS处理

### ISSUE THREAD

**Issue by wangxi1998** [XiaoLinhong/uplandsue#1]
有些WPS处理的数据来源问题想向您请教，利用您账号显示的邮箱未能联系上您，请问方便提供联系方式吗？
我的邮箱是1553638571@qq.com

**Comment by XiaoLinhong** [comment]
抱歉，好久没有登录学校的有效，最近我会经常看，可以直接用邮箱联系我

**Comment by wangxi1998** [comment]
***@***.***
我之前有给您发过邮件请教问题，我再发一遍发给您吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月6日(星期三) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XiaoLinhong/uplandsue] 请教WPS处理 (Issue #1)





 
抱歉，好久没有登录学校的有效，最近我会经常看，可以直接用邮箱联系我
